name: "cdktf action"
description: "execute cdktf action"
inputs:
  stackName:
    required: true
  mode:
    required: true
  terraformCloudToken:
    required: true
  githubToken:
    required: true

runs:
  using: "composite"
  steps:
    - uses: actions/setup-node@v3
      with:
        node-version-file: '.node-version'
      working-directory: infra

    # TODO: cache

    - name: Install dependencies
      run: npm install
      working-directory: infra

    - name: Run Terraform CDK
      uses: hashicorp/terraform-cdk-action@v0.1
      with:
        # バージョンはデフォルト値が妙に古いので、明示的に指定する
        terraformVersion: 1.5.4
        cdktfVersion: 0.16.1
        stackName: ${{ inputs.stackName }}
        mode: ${{ inputs.mode }}
        commentOnPr: false
        terraformCloudToken: ${{ inputs.terraformCloudToken }}
        githubToken: ${{ inputs.githubToken }}
      working-directory: infra
