services:
  app:
    build:
      context: app
    ports: ["8080:8080"]
    environment:
      PORT: 8080
      PROJECT_ID:
      AUTH_PATH: local
      BASIC_USER: user
      BASIC_PASS: pass
      SWITCHBOT_TOKEN:
      SWITCHBOT_SECRET:
