version: "3"
services:
  app:
    build:
      context: app
    volumes:
      - ./app:/go/src/app
    command: ./app

  redis:
    image: redis:6.2.7-alpine
    ports:
      - 6379:6379

  influxdb:
    image: influxdb:2.4.0-alpine
    ports:
      - 8086:8086

  telegraf:
    image: telegraf:1.23.4-alpine
    ports:
      - 3000:3000
