- hosts: all
  vars:
    recorder_url: "{{ lookup('env', 'RECORDER_URL') }}"
  tasks:
    - name: reduce journalctl log size
      # systemctl status などが遅すぎるのを防ぐ refs #75
      become: true
      block:
        - lineinfile:
            path: /etc/systemd/journald.conf
            regexp: "^#?SystemMaxUse="
            line: "SystemMaxUse=50M"
        - systemd:
            name: systemd-journald
            state: restarted
    - name: setup bluepy
      become: true
      block:
        - apt:
            pkg:
              - python3-pip
              - libglib2.0-dev
        - pip:
            name: bluepy

    - name: deploy scanner code
      block:
        - become: true
          file:
            path: /opt/scanner
            state: directory
            owner: "{{ ansible_env.USER }}"
            group: "{{ ansible_env.USER }}"
        - copy:
            src: files/scanner.py
            dest: /opt/scanner/scanner.py
    - name: deploy scanner service
      become: true
      block:
        - copy:
            src: files/scanner.service
            dest: /etc/systemd/system/scanner.service
        - systemd:
            enabled: true
            state: restarted
            daemon_reload: true
            name: scanner

    - name: deploy record
      become: true
      block:
        # record.env は手動で設置・値書き込みする
        - copy:
            src: files/record.sh
            dest: /opt/scanner/record.sh
            mode: "0755"
        - cron:
            name: record
            job: "/opt/scanner/record.sh"
            minute: "*" # every minute

    - name: deploy retry
      become: true
      block:
        - copy:
            src: files/retry.sh
            dest: /opt/scanner/retry.sh
            mode: "0755"
        - cron:
            name: record
            job: "/opt/scanner/retry.sh"
            minute: "0" # every hour
