name: infra-plan
on:
  pull_request:
    paths:
      - .github/workflows/infra-plan.yml
      - infra/**
  workflow_dispatch:
    inputs:
      environment:
        type: environment
permissions:
  id-token: write
  contents: read
  pull-requests: write

jobs:
  invoke:
    runs-on: ubuntu-22.04
    environment: ${{ inputs.environment || 'staging' }}
    # npm install, synth, refresh stateが重なると遅くなる可能性があるため、長めに設定
    timeout-minutes: 20
    defaults:
      run:
        working-directory: infra
    steps:
      - uses: actions/checkout@v4

      - uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: "projects/${{ secrets.GCP_PROJECT_NUMBER }}/locations/global/workloadIdentityPools/ghactions-pool/providers/ghactions-provider"
          service_account: "ghactions@${{ secrets.GCP_PROJECT_ID }}.iam.gserviceaccount.com"

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.8.1"
          terraform_wrapper: false

      - name: setup tfcmt
        run: |
          VERSION=v4.9.0
          curl -L https://github.com/suzuki-shunsuke/tfcmt/releases/download/${VERSION}/tfcmt_linux_amd64.tar.gz | tar xz -C /tmp
          mv /tmp/tfcmt /usr/local/bin

      - uses: actions/setup-node@v4
        with:
          node-version-file: infra/.node-version
      - uses: actions/cache@v4
        with:
          path: infra/node_modules
          key: node_modules-${{ hashFiles('infra/package-lock.json') }}
      - run: npm install

      - run: npm run synth
      - run: terraform init
        working-directory: infra/cdktf.out/stacks/${{ vars.INFRA_ENV }}
      - run: tfcmt plan --patch -- terraform plan -no-color
        working-directory: infra/cdktf.out/stacks/${{ vars.INFRA_ENV }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TF_VAR_project_id: ${{ secrets.GCP_PROJECT_ID }}
