name: infra-plan
on:
  pull_request:
    paths:
      - .github/workflows/infra-plan.yml
      - infra/**
  workflow_dispatch:
    inputs:
      environment:
        type: environment
permissions:
  id-token: write
  contents: read

jobs:
  invoke:
    runs-on: ubuntu-22.04
    environment: ${{ inputs.environment || 'development' }}
    # npm install, synth, refresh stateが重なると遅くなる可能性があるため、長めに設定
    timeout-minutes: 20
    defaults:
      run:
        working-directory: infra
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: infra/.node-version
      - uses: actions/cache@v4
        with:
          path: infra/node_modules
          key: node_modules-${{ hashFiles('infra/package-lock.json') }}
      - run: npm install

      - uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: "projects/${{ secrets.GCP_PROJECT_NUMBER }}/locations/global/workloadIdentityPools/ghactions-pool/providers/ghactions-provider"
          service_account: "ghactions@${{ secrets.GCP_PROJECT_ID }}.iam.gserviceaccount.com"

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "~1.6.0"
          terraform_wrapper: false

      - run: npm run synth
      - run: terraform init
        working-directory: infra/cdktf.out/stacks/${{ vars.INFRA_ENV }}
      - run: terraform plan -no-color
        working-directory: infra/cdktf.out/stacks/${{ vars.INFRA_ENV }}
        env:
          TF_VAR_project_id: ${{ secrets.GCP_PROJECT_ID }}
