name: PR_cdktfのsynth確認

on:
  push:
    branches: [main]
  pull_request:
    # recorderやviewerの変更がある場合もterraform差分は発生するため、pathsをinfraに限定しない

jobs:
  check:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    defaults:
      run:
        working-directory: infra
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version-file: 'infra/.node-version'
      - uses: actions/cache@v3
        with:
          path: 'node_modules'
          key: infra-node_modules-${{ hashFiles('**/package-lock.json') }}
      - run: npm install

      # synthによりdiffが発生すればexit-codeが1になる
      - run: cat cdktf.out/stacks/development/assets/CloudFunctionGo_recorder_zip_2313AB52/9FA5F3A1FF8E727ADBABE9AB0E8FD8C6/archive.zip | sha256sum
      - run: npm run synth
      - run: cat cdktf.out/stacks/development/assets/CloudFunctionGo_recorder_zip_2313AB52/9FA5F3A1FF8E727ADBABE9AB0E8FD8C6/archive.zip | sha256sum
      # - run: git diff --exit-code
